### ISSUE TITLE
Check issued-at timestamp is failing

### ISSUE THREAD

**Issue by jeffm13** [pingidentity/lua-resty-openidc#1]
The lua-resty-openidc plugin is failing for us on simple requests. The problem is likely caused by differences in time synch and/or latency between our Ping server and our app servers running on AWS & Verizon clouds.

We're seeing the following message in our logs:  

2015/09/29 19:30:56 [error] 18972#0: *4 [lua] openidc.lua:90: openidc_validate_id_token(): token is not valid yet: id_token.iat=1443554983, os.time()=1443555056, client: <client_ip>, server: , request: "GET /redirect_uri?state=<state value>&code=<code value> HTTP/1.1", host: "<server_ip:port>"

Increasing the value in the script to 1000 fixes the problem for us. Is there a reason for the hard-coded 10ms value in the script?  Is it reasonable to increase that value or to parameterize it so that implementations can override in config files?

**Comment by zandbelt** [comment]
Yes, a configurable value makes sense. Do notice that the time is in seconds so you've now set the "slack" interval to 1000 seconds which may be a bit more that you should allow for security-wise as the offset between client and server in your case is 73 seconds.
