### ISSUE TITLE
openidc breaks with latest update

### ISSUE THREAD

**Issue by Phrozyn** [pingidentity/lua-resty-openidc#100]
installed lua-resty-openidc-1.4.0 - now the app no longer even tries to connect to our auth provider.
So I reverted the openidc.lua to 1.3.1
Now I get this message:

openidc_layer.lua:26: no error was returned but session is not set. A possible cause is that you're using lua-resty-openidc 1.3.1 or earlier which do not have the required features. If lua-resty-openidc 1.3.2 or newer is available, please upgrade. If lua-resty-openidc 1.3.2 has not yet been released, you can find the needed functionality in https://github.com/pingidentity/lua-resty-openidc/commit/7bafac883264ac4d33a8a83da7040a74024ca08f or newer.

However, it at least connects to the auth provider and allows us to login - otherwise we cannot.
I've  tried with the version from the commit but it also does not work.

**Comment by gdestuynder** [comment]
openidc_layer.lua is a mozilla specific wrapper - that said, the change is that lua-resty-openidc no longer return the session, which prevents the wrapper from seeing or touching it, which breaks functionality when upgrading

**Comment by Phrozyn** [comment]
Thanks @gdestuynder!!
