### ISSUE TITLE
should openidc (optionally) verify the access token after the token request?

### ISSUE THREAD

**Issue by bodewig** [pingidentity/lua-resty-openidc#103]
Clients can use `openidc.jwt_verify` to verify access tokens.

If you know the access token must be a JWT you currently invoke `openidc.authenticate`, extract the access token and then invoke `openidc.jwt_verify` from some wrapper code. Would it be a good idea to add an option that tells `authenticate` to verify the access token internally when it is received?

**Comment by zandbelt** [comment]
I don't follow: openidc.authenticate doesn't call jwt_verify AFAICT.

**Comment by bodewig** [comment]
You are correct, it doesn't. But it could :-)

My scenario is I use `openidc.authenticate` and know the access token is a JWT. If I had obtained it from the client I'd pass it through `openidc.jwt_verify`. If I want to verify the access token after `openidc.authenticate` I have to do so manually. I was wondering whether a convenience option "please verify the access token assuming it is a JWT` could remove this manual step.

This might be feature creep and I'd understand it if you didn't want to see it happen.

**Comment by zandbelt** [comment]
There *really* shouldn't be any need for this. In fact I think it would put people on the wrong path...

**Comment by bodewig** [comment]
Because it would encourage clients trying to do anything with the access token that they aren't supposed to, understood.
