### ISSUE TITLE
Access Token no more returned by `openidc.authenticate` if `renew_access_token_on_expiry` is set to `false`

### ISSUE THREAD

**Issue by pamiel** [pingidentity/lua-resty-openidc#121]
The just issued 1.5.0 version introduces a new parameter named `renew_access_token_on_expiry`.

When testing the behavior of this new param, I faced the following issue: if this parameter is set to `false`, then the Access Token is no longer returned as output data of the `openidc.authenticate` function.

My analysis is the following:
- The pure login process still works fine, until the redirection to the redirect_ui. At that stage, the Access Token is correctly retrieved and stored in the session.
- When the last redirect to the original uri is done, the `openidc.authenticate` is called again: processing of this method first checks whether it is the redirect_uri (no, it is not); then if it is the logout uri (no, it is not) => the new code starting in line 955 is run!
- As the `renew_access_token_on_expiry` is set to `false`, the `try_to_renew`local varaiable is `false`, so the `if` statement of line 957 if never evaluated to `true`
- So the `openidc_access_token` function is never called, and the `access_token` local variable remains nil...
- ... So Access Token can never be returned as output data of `openidc.authenticate` (lines 1003 to 1011).

**Comment by zandbelt** [comment]
Thanks for reporting. Can you try this branch: https://github.com/pingidentity/lua-resty-openidc/compare/fix-access-token-return and let us know if that fixes it?

**Comment by bodewig** [comment]
ahh, sprry about that. Fix looks good to me.

**Comment by pamiel** [comment]
Works better: Access Token is now available... but I'm still not sure the library behaves in a proper way: when the Access Token expires, the (expired) Access Token is still returned as output data of the `openidc.authenticate` => the access to the resource looks still allowed, unless the caller explicitly checks the expiration date of the token !!

My feeling is that in case the Access Token expires and it is not requested to refresh it, then `openidc.authenticate` shall return a non nil `err`.


In terms of implementation, my 2 cents: why do you manage the `renew_access_token_on_expiry` in the `openidc.authenticate` function? It looks to me more obvious to manage it in the `openidc_access_token` function because this function has the clear responsibility to deliver either a valid Access Token (the non-expired one available in the session, or a refreshed one in case the token has expired and the `renew_access_token_on_expiry` is set to true), or nil in case of expired token with `renew_access_token_on_expiry` set to false or in case of error getting the token.
Would need to rollback the updates done in `openidc.authenticate` and move the `try_to_renew` stuff in the `openidc_access_token` function, **after** the check of the expiration time.

**Comment by zandbelt** [comment]
I'm leaving this to @bodewig but I would like to emphasize that the `expires_in` as returned in the authentication response is merely a hint and should not be used in an "absolute" way, but just to optimize the user experience. At any time an access token can expire or be invalidated by the authorization server.

**Comment by bodewig** [comment]
when moving the decision into `openidc_access_token` it would also apply to `openidc.access_token` unless we make it an explicit parameter.

`try_to_refresh` not only controls whether to refresh the token but also what happens when the token expires in `authenticate`. If it is true when the token expires then `authenticate` re-runs the authorization flow, if its false this will not happen.

A slightly amended fix is in c131305 which would also allow us to use the flag in `openidc.auccess_token` if we wanted to.

**Comment by zandbelt** [comment]
agreed, you approach looks better

**Comment by bodewig** [comment]
@pamiel what my change does not do is returning `err` in the case when the token expires. This is to be consistent with the behavior of 1.4.1 which also wouldn't return an error if the token expired and no refresh token was available.

**Comment by pamiel** [comment]
@bodewig I'm in line with your last update: `try_to_refresh` evaluated in `openidc.authenticate` but test of expiration done in `openidc_access_token` function.
And it now takes into account the `access_token_expires_leeway` which was not the case before.

For the fact that it does not return an `err`: I understand that it is backward compatible... but still, I think it would have been better to raise en `err` here... Anyway, we are now able to check if `res.access_token` is nil or not => it is manageable at library caller side.

**Comment by bodewig** [comment]
OK, fix merged to master.
