### ISSUE TITLE
Create Lua Rocks profile

### ISSUE THREAD

**Issue by asbjornu** [pingidentity/lua-resty-openidc#17]
As mentioned in #13, someone in Ping Identity should create a profile on Lua Rocks so the [current rock](https://luarocks.org/modules/asbjornu/lua-resty-openidc) can be moved from my personal account to something a bit more official.

**Comment by zandbelt** [comment]
I created this https://luarocks.org/modules/hanszandbelt/lua-resty-openidc

**Comment by asbjornu** [comment]
@zandbelt Excellent! Have you entered the `API_KEY` from Lua Rocks into Travis as well?

**Comment by zandbelt** [comment]
yes, I did

**Comment by asbjornu** [comment]
@zandbelt :+1:
