### ISSUE TITLE
INTERNAL SERVER ERROR 500.

### ISSUE THREAD

**Issue by Twinko5** [pingidentity/lua-resty-openidc#18]
Hello there, 

I get an internal server error with nothing in my logs, so it is kinda hard to debug. 
My config file works without the require("resty.openidc") line.

As soon as I add this line, the whole thing crashed. 

I setted : lua_package_path '/usr/local/openresty/lualib/resty/?.lua;;';
I got the openidc.lua file in the package path above.

I can't see what's wrong .. 

I am quite new to this, so it might be pretty simple, I am still not sure the way I add package is the good one ..

Please help me.
Thanks in advance for your time,
Twinko5

**Comment by zandbelt** [comment]
try and enable debug logging with something like:
````
error_log logs/error.log debug;
````

**Comment by Twinko5** [comment]
Thanks for your answer, I actually had these logs, but there were informations in the old nginx logs, so I used these and was able to debug it.

It works as it is supposed to now !
Great work guys, thanks !
