### ISSUE TITLE
If session does not match, redirect omits port

### ISSUE THREAD

**Issue by dholth** [pingidentity/lua-resty-openidc#19]
I'm using https://localhost:8443/ as a test server. It looks like a redirect on the error path drops the port.

1. Set lua_code_cache off without setting an explicit session secret. This causes resty.session to choose a new secret for every request, and it will not be able to decode session cookies.
2. Visit protected URL, get redirected to IdP
3. Redirect back to callback URL
4. Redirect to https://localhost/ with no port

**Comment by zandbelt** [comment]
Which version are you using? When I try this, my browser displays:

> state from argument: 0b40bbc313e93469abd7e08b7023fd18 does not match state restored from session: nil

on the callback URL that has the correct port, which is the expected result.

**Comment by dholth** [comment]
Cloned it straight off github:
lua-resty-openidc 1.2.0-1
lua-resty-session 2.8-1
lua-crypto 0.3.2-2
lua-resty-hmac 1.0-1
lua-resty-jwt 0.1.5-0
lua-resty-http 0.08-0

**Comment by zandbelt** [comment]
What does your `nginx.conf` look like?

As you'll note after opening the session in https://github.com/pingidentity/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L460 the authorization response handler just returns to the caller on a session restore error: https://github.com/pingidentity/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L295, no redirects involved.

Could it be that the calling configuration somehow redirects after `local res, err = require("resty.openidc").authenticate(opts)` returns with `err` set?

**Comment by dholth** [comment]
Thank you so much for looking at it. I've solve the problem in a different way, by doing port redirection so that :443 can work even in the development environment. Here are my config files.

```nginx

#user  nobody;
worker_processes  1;

error_log  logs/error.log debug;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    resolver 8.8.8.8;

    lua_ssl_trusted_certificate /etc/pki/tls/certs/ca-bundle.crt;
    lua_ssl_verify_depth 5;
    lua_code_cache off; # debugging
    lua_shared_dict discovery 1m;
    lua_shared_dict introspection 10m;

    include       mime.types;
    default_type  application/octet-stream;

    ssl_protocols       TLSv1.1 TLSv1.2;
    ssl_ciphers         "ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS";
    ssl_prefer_server_ciphers on;

    gzip on;
    gzip_proxied any;
    proxy_buffering on;

    sendfile        on;
    keepalive_timeout  65;

    server {
        # needed for lua-resty-session
        set $session_secret secret;

        listen       80;
        listen       443 ssl http2;
        server_name  localhost;

        ssl_protocols       TLSv1.1 TLSv1.2;
        ssl_ciphers         "ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS";
        ssl_prefer_server_ciphers on;
        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_certificate     /etc/pki/tls/certs/Certificate.pem;
        ssl_certificate_key /etc/pki/tls/private/Certificate.key;

        location / {
            access_by_lua_file "conf/access.lua";
                
            root   html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
}
```

access.lua
```lua
local opts = {
    -- the full redirect URI must be protected by this script and becomes:
    -- ngx.var.scheme.."://"..ngx.var.http_host..opts.redirect_uri_path
    -- unless the scheme is overridden using opts.redirect_uri_scheme or an X-Forwarded-Proto header in the incoming request
    redirect_uri_path = "/oauth2/callback",
    discovery = "https://accounts.google.com/.well-known/openid-configuration",
    client_id = "abc,
    client_secret = "123",
    scope = "openid email profile"
}

-- call authenticate for OpenID Connect user authentication
local res, err = require("resty.openidc").authenticate(opts)
local cjson = require("cjson")
if res then
    ngx.header.content_type = "text/plain; encoding=utf-8"
    ngx.say(cjson.encode(res))
end
```

**Comment by zandbelt** [comment]
in your config there's no action when `err` is set so the redirect must have come from thereafter
