### ISSUE TITLE
lua_ssl_trusted_certificate

### ISSUE THREAD

**Issue by consultantRR** [pingidentity/lua-resty-openidc#2]
This may be a daft question, but what certificate is this supposed to be?

`lua_ssl_trusted_certificate /opt/local/etc/openssl/cert.pem`

Clearly I am not using the right one, as this is what I see in the nginx error logs:

```
2016/01/10 07:12:36 [alert] 20456#0: *1 ignoring stale global SSL error (SSL: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt), client: IP_REDACTED, server: REDACTED.com, request: "GET / HTTP/1.1", host: "REDACTED.com"
2016/01/10 07:12:36 [error] 20456#0: *1 lua ssl certificate verify error: (20: unable to get local issuer certificate), client: IP_REDACTED, server: REDACTED.com, request: "GET / HTTP/1.1", host: "REDACTED.com"
```

**Comment by zandbelt** [comment]
a file with the trusted CA certificate(s), see: https://github.com/openresty/lua-nginx-module#lua_ssl_trusted_certificate

**Comment by consultantRR** [comment]
Thanks, I actually read that before posting, and I am still not 100% clear on:

"the certificate of the SSL/TLS server in the tcpsock:sslhandshake method."

So, the CA of the SSL cert on _my_ server, or the CA of the cert on Google's server?

Does this need to be the full chain (with any/all intermediate certs, or just the top level CA?

**Comment by zandbelt** [comment]
The CA of the cert on Google's server; that file needs only top level CA(s.) This is no different than in any OpenSSL setup.

**Comment by wstrange** [comment]
For those on Ubuntu/Debian (or Docker derivations of those), the common root certificates can be installed via:

apt-get install ca-certificates
They will be placed in /etc/ssl/certs

The file ca-certificates.crt is probably what you want

**Comment by steve-chavez** [comment]
Managed to sort this out in `openresty/openresty:jessie` docker container by doing:
```bash
## In Dockerfile
RUN cp /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.pem
## Then in nginx.conf
lua_ssl_verify_depth 2;
lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.pem;
```
