### ISSUE TITLE
Add validation of hd param in id_token 

### ISSUE THREAD

**Issue by dtabwhite** [pingidentity/lua-resty-openidc#22]
Step 5 of validating and ID token listed over here: https://developers.google.com/identity/protocols/OpenIDConnect#validatinganidtoken

says:

```
If you passed a hd parameter in the request, verify that the ID token has a hd claim that matches your Google Apps hosted domain.
```

It seems like this functionality is missing from `openidc_validate_id_token` here:

https://github.com/pingidentity/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L87

Without this is seems like it's not possible to restrict login access to a particular google apps domain.

**Comment by zandbelt** [comment]
That's a Google specific extension/implementation of OpenID Connect so it cannot/shouldnot not be handled in the generic OpenID Connect code; instead what you should do is enforce it on the configuration level with something like:

    if res.id_token.hd ~= "pingidentity.com" then
        ngx.exit(ngx.HTTP_FORBIDDEN)
    end

That is documented in the README.md here https://github.com/pingidentity/lua-resty-openidc#sample-configuration-for-google-signin in the section about Google+ Signin.
