### ISSUE TITLE
Install via Luarocks

### ISSUE THREAD

**Issue by danthegoodman** [pingidentity/lua-resty-openidc#23]
I would like to install this library via luarocks. My attempts to install the library are failing, saying that no match was found.

```
luarocks install lua-resty-openidc
```

It looks like this is failing because the module https://luarocks.org/modules/hanszandbelt/lua-resty-openidc isn't included in any manifests.

**Comment by zandbelt** [comment]
I've opened an issue here: https://github.com/leafo/luarocks-site/issues/97

**Comment by zandbelt** [comment]
should be fixed now

**Comment by danthegoodman** [comment]
Awesome. Thank you! 👍
