### ISSUE TITLE
constant ssl errors

### ISSUE THREAD

**Issue by davidbirdsong** [pingidentity/lua-resty-openidc#26]
I'm sure this si not related to this lib, but I'm hoping to get some direction here. Nothing's changed on my proxy that I use this lib on that enables a general purpose google auth proxy, but I'm seeing these errors after 5-10 seconds after authenticating in the debug log and it's rendering this proxy unusable.

Any clues?

```
2016/10/25 20:03:18 [alert] 26406#0: ignoring stale global SSL error (SSL: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt)
```

**Comment by zandbelt** [comment]
I believe the last comment in this thread may help you:
https://github.com/bungle/lua-resty-session/issues/23

**Comment by davidbirdsong** [comment]
Thanks, I also disabled redis as a store and went to cookie and so far it seems to work much more reliably.

**Comment by zandbelt** [comment]
If you can isolate the problem to redis or something else it would be good to report in the lua-resty-session repo.

**Comment by mateodelnorte** [comment]
I'm getting this issue repeatedly with the redis provider. Would love to know if there is a solution for using redis, or if redis is inducing this error due to a session data size limitation particular to redis.

Have any concrete answers emerged?
