### ISSUE TITLE
Build Error Failed installing lib/resty/openidc.lua

### ISSUE THREAD

**Issue by trevrobwhite** [pingidentity/lua-resty-openidc#27]
Hi Ping Identity, 
I'm just trying to set up one of our Ubuntu 14.04 Servers running Nginx up to use OpenID Connect.

It's a plain installation, I've tried installing OpenRusty (I wasn't sure if this was a requirement) and luarocks.

I can only get as far in the installation as:
lua-resty-http 0.08-0 is now built and installed in /usr/local/ (license: 2-clause BSD)
cp: cannot stat ‘lib/resty/openidc.lua’: No such file or directory

Error: Build error: Failed installing lib/resty/openidc.lua in /usr/local/lib/luarocks/rocks/lua-resty-openidc/1.2.1-1/lua/resty

Any ideas how to get past this part?  I've followed the information in the readme.md

Many thanks.

**Comment by zandbelt** [comment]
@asbjornu perhaps could you have a look?

**Comment by asbjornu** [comment]
@trevrobwhite: Please have a look at [`.travis.yml`](https://github.com/pingidentity/lua-resty-openidc/blob/master/.travis.yml), which is used as configuration on how to install and build everything on Travis.

**Comment by zandbelt** [comment]
@asbjornu I believe the difference is that @trevrobwhite installs from luarocks directly rather than from a locally created rock; I am able to reproduce this behaviour on a clean Ubuntu install

**Comment by asbjornu** [comment]
@zandbelt: I've only ever tried to install it in Docker. Perhaps that doesn't work anymore either? With #16, we could have a continuous integration test for a consumer (the Docker image) of the Lua Rock. Without that, I guess we need to set up something on Travis, but I don't know how to do that, as mentioned here: https://github.com/pingidentity/lua-resty-openidc/pull/16#issuecomment-238055830

**Comment by zandbelt** [comment]
I can use this to reproduce it on Docker:
```
FROM ubuntu:trusty

RUN apt-get clean && apt-get --fix-missing update
RUN apt-get install -y nginx luarocks git libssl-dev
RUN luarocks install lua-resty-openidc
```

it will install all the dependencies and then fail with:
```
  inflating: lua-resty-http/lib/resty/http_headers.lua  
Updating manifest for /usr/local/lib/luarocks/rocks

lua-resty-http 0.08-0 is now built and installed in /usr/local/ (license: 2-clause BSD)
cp: cannot stat 'lib/resty/openidc.lua': No such file or directory

Error: Build error: Failed installing lib/resty/openidc.lua in /usr/local/lib/luarocks/rocks/lua-resty-openidc/1.2.1-1/lua/resty
The command '/bin/sh -c luarocks install lua-resty-openidc' returned a non-zero code: 1
```

**Comment by asbjornu** [comment]
I see. This worked when I first set up the Docker image and I'm not sure what's happened since. As there are no automated tests to catch breaks like this, it's hard to figure out when the problem first occurred.

**Comment by zandbelt** [comment]
https://github.com/pingidentity/lua-resty-openidc/compare/0e50e4f19aa42a2e6f7629606f68e88b26733961...master

seems that the only relevant change is the last change in that diff:
```
-        openidc = "lib/resty/openidc.lua"
+        ["resty.openidc"] = "lib/resty/openidc.lua"
```
although that would not be important to the file path for the installation AFAIK

**Comment by zandbelt** [comment]
it actually looks like it never worked since `RUN luarocks install lua-resty-openidc 1.2.0` also results in an error...

**Comment by trevrobwhite** [comment]
I only installed luarocks because it seemed to be easiest way to get this up and running according to the readme. 

My server is a completely a blank ubuntu 14.04.05 Server LTS with apache removed and nginx, php and MySQL installed which I want to authenticate against our ping identity SSO server using OpenID Connect. 

I want to keep the overhead as small as possible so any modules I don't need to install the better. 

Many thanks.

**Comment by zandbelt** [comment]
the latest commit seems to fix this issue for my Docker build; can you test/confirm? (the rockspec version is now 1.2.1-2)

**Comment by trevrobwhite** [comment]
The new version works perfectly, many thanks.

@zandbelt I've dropped you a mail wondering if you can assist in converting my apache configuration file to nginx.

Very grateful if you have time, thank-you.
