### ISSUE TITLE
State from argument does not match state restored from session

### ISSUE THREAD

**Issue by vavra5** [pingidentity/lua-resty-openidc#284]
###### Environment

- lua-resty-openidc version 1.7.2
- OpenID Connect provider Okta
- OpenResty docker container

###### Expected behaviour

Logged in already.

###### Actual behaviour
I get the following error when clicking on an external link (ex. outside of the browser window in PowerPoint).  
![error](https://user-images.githubusercontent.com/1078886/63866106-b6b7b380-c980-11e9-8f3c-e56e5833f818.PNG)

###### Minimized example
I create a custom OpenResty docker image that adds my nginx.conf and lua-resty-openidc.conf. I'm using docker-compose to start the environment.

Steps to reproduce:
1. In Chrome navigate to http://localhost
2. http://localhost is redirected to https://dev-######.okta.com/login/login.htm?......
3. Login with credentials
4. Redirected back to http://localhost
5. Valid tokens exist
6. Open PowerPoint (or any external application)
6. Click a url/link in application with url = "http://localhost"
7. Link opens in new Chrome tab with url = "http://localhost/redirect_uri?code=rsECWm-c8dahcFS85xfU&state=75d4e8455bffd0e268c7f4d4cd9e2f67"
8. Error on page reads "ERR_INVALID_RESPONSE"

###### Configuration and NGINX server log files

**lua-resty-openidc.conf:** 

    lua_package_path '/usr/local/openresty/lualib/resty/?.lua;;';

    lua_package_cpath '/usr/local/openresty/lualib/resty/?.so;;';

    lua_shared_dict discovery 1m;
    lua_shared_dict jwks 1m;
    lua_ssl_verify_depth 5;
    lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;

    resolver 127.0.0.11 8.8.8.8 ipv6=off;
    
    server {
        access_log /usr/local/openresty/nginx/logs/access.log main;

        error_log /usr/local/openresty/nginx/logs/error.log debug;

        server_name  localhost;

        listen 80 default_server;
        set $session_secret             ${SESSION_SECRET};
        location / {

            access_by_lua_block {
                local opts = {
                    redirect_uri = "/redirect_uri",
                    discovery = "${DISCOVERY_URL}",
                    client_id = "${CLIENT_ID}",
                    client_secret = "${CLIENT_SECRET}",
                    redirect_uri_scheme = "http",
                    logout_path = "/logout",
                    post_logout_redirect_uri = "http://localhost/",
                    redirect_after_logout_with_id_token_hint = true,
                    renew_access_token_on_expiry = true,
                    ssl_verify = "yes",
                    accept_unsupported_alg = false,
                    token_signing_alg_values_expected = { "RS256" },
                    access_token_expires_leeway = 30,
                    revoke_tokens_on_logout = true,
                    token_endpoint_auth_method = "client_secret_basic"
                }

                local res, err = require("resty.openidc").authenticate(opts)
                if err then
                    ngx.status = 403
                    ngx.say(err)
                    ngx.exit(ngx.HTTP_FORBIDDEN)
                end
            }

            expires           0;
            add_header        Cache-Control private;
            proxy_pass  http://hello;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

        }
    }

**nginx.conf**

    worker_processes  1;

    error_log /usr/local/openresty/nginx/logs/error.log debug;

    events {
        worker_connections 1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] '
                        '"$request" $status $bytes_sent '
                        '"$http_referer" "$http_user_agent"';

        access_log /usr/local/openresty/nginx/logs/access.log  main;

        sendfile        on;

        keepalive_timeout  65;

        include /etc/nginx/conf.d/lua-resty-openidc.conf;
    }

**Dockerfile**

	FROM openresty/openresty:1.15.8.2-1-alpine-fat

	# Install ca-certificates
	RUN apk update && apk add --no-cache curl perl ca-certificates && rm -rf /var/cache/apk/*

	RUN update-ca-certificates -f -v

	# install dependencies
	RUN ["opm", "get", "zmartzone/lua-resty-openidc=1.7.2"]

	# nginx main config
	ADD nginx.conf /usr/local/openresty/nginx/conf/nginx.conf

	# nginx primary vhost
	ADD lua-resty-openidc.template /etc/nginx/conf.d/lua-resty-openidc.template

	# template configuration
	CMD ["/bin/bash","-c","envsubst \"`for v in $(compgen -v);do printf '${%s} ' $v;done`'\" < /etc/nginx/conf.d/lua-resty-openidc.template > /etc/nginx/conf.d/lua-resty-openidc.conf && /usr/local/openresty/bin/openresty -g 'daemon off;'"]

	EXPOSE 80 443

	STOPSIGNAL SIGQUIT

**docker-compose.yml**

	version: '3'
	services:
	  openidc:
		build:
		  context: ./
		  dockerfile: Dockerfile
		image: openidc:local
		container_name: openidc
		restart: on-failure
		environment:
		  CLIENT_ID: removed
		  CLIENT_SECRET: removed
		  DISCOVERY_URL: removed
                  SESSION_SECRET: removed
		ports:
		- "80:80"
		expose:
		- 80
		links:
		- hello
	  hello:
		image: nginxdemos/hello:latest
		container_name: hello
		restart: on-failure
		ports:
		- "8400:80"
		expose:
		- 8400

**Comment by zandbelt** [comment]
that appears to be a local (shared cookie) integration issue between word and your browser that cannot be fixed in this plugin

**Comment by zandbelt** [comment]
It would be great if you could narrow it down. Thanks.

**Comment by vavra5** [comment]
@zandbelt  I just wanted to follow up in case anyone comes across this issue.  I've implemented the fix below for Nginx in the location block and it passes some of the tests I've done using PowerPoint and Excel.

`if ($http_user_agent ~* Word|Excel|PowerPoint|ms-office) {
        return 200 '<html><head><meta http-equiv="refresh" content="0"/></head><body></body></html>';
        }`

**Comment by zandbelt** [comment]
thanks for reporting back!
