### ISSUE TITLE
Where should I put OIDCCryptoPassphrase ?

### ISSUE THREAD

**Issue by dimitrovs** [pingidentity/lua-resty-openidc#30]
I am migrating from the mod_auth_openidc Apache plugin to lua-resty-openidc with Nginx. In Apache I had my OAuth2 provider JsonWebToken Signature Algorithm set to RS256. With this setting the lua-resty-openidc module is in a redirect loop with the OAuth2 provider. I changed the algorithm to HS256 and now the first request authenticates fine but subsequent requests trigger authentication redirect (it appears session is not being kept). In the logs I have:

`ignoring stale global SSL error (SSL: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt)`

and I saw your response to #26 so I tried setting:

`set $session_cipher none;`

no difference, first request is authenticated, subsequent requests trigger authentication.

Also tried:

`set $session_secret 623q4hR325t36VsCD3g567922IC0073T;`

and no difference.

I am trying to move away from mod_auth_openidc because websockets are not working when both Apache & Nginx are involved (I need some Nginx-specific features). In Apache I had OIDCCryptoPassphrase and I am not sure where to put this variable in lua-resty-openidc or if it is related to the problem at all...

**Comment by zandbelt** [comment]
`$session_secret`  is basically doing what `OIDCCryptoPassphrase ` is. Can you paste the full debug  log and provide the version of lua-resty-openidc that you are using?

**Comment by dimitrovs** [comment]
The logs are too big, I couldn't paste them, but I uploaded them here: https://github.com/dimitrovs/lua-resty-openidc-problem/blob/master/error.log

I also uploaded my config: https://github.com/dimitrovs/lua-resty-openidc-problem/blob/master/nginx.conf

And I am using the version from the master branch of lua-resty-openidc and its dependecies.

**Comment by dimitrovs** [comment]
The problem was with lua-resty-session . I cloned their master branch and it appears there is some bug in it because the session was getting lost. Switched to lua-resty-session Release 2.13 and the problems were resolved. Thank you for the great plugin.
