### ISSUE TITLE
"require claim" support?

### ISSUE THREAD

**Issue by nynymike** [pingidentity/lua-resty-openidc#31]
Is there any way to specify if a claim is required, for example if a person has a certain value for role?

**Comment by zandbelt** [comment]
By the time `require("resty.openidc").authenticate(opts)` finishes, you can execute any logic you want in the Lua scripting language on the result of that. An example can be found in the `README.md`
```
          local res, err = require("resty.openidc").authenticate(opts)

          if err then
            ngx.status = 500
            ngx.say(err)
            ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
          end

          -- at this point res is a Lua table with 3 keys:
          --   id_token    : a Lua table with the claims from the id_token (required)
          --   access_token: the access token (optional)
          --   user        : a Lua table with the claims returned from the user info endpoint (optional)
[snip]
          --if res.user.email ~= "hzandbelt@pingidentity.com" then
          --  ngx.exit(ngx.HTTP_FORBIDDEN)
          --end
```

**Comment by nynymike** [comment]
Thanks for the quick response! What about post-authentication. For example, let's say I authn accessing a folder `/folder1` and then I traverse to `/folder2`. Maybe this second folder is actually a different applicationk with different a different claims requirement.

**Comment by zandbelt** [comment]
You can use a similar `access_by_lua` clause; the authenticate call will return immediately as a session exists.

**Comment by zandbelt** [comment]
assuming that did the trick otherwise you can reopen
