### ISSUE TITLE
Infinite authentication loop

### ISSUE THREAD

**Issue by hanikesn** [pingidentity/lua-resty-openidc#33]
With 1.2.3 the encrypted id_token is saved in the session data (#29). This pushes the session cookie size above 4 kb with e.g. Azure Active Directory and thus the cookie will not be stored by most browsers.

Possible workarounds are to use a different session store. Using a gzip based session encoder might also be an option.

**Comment by hanikesn** [comment]
Compressing the cookie with gzip brought it down to 3822 bytes. Maybe it makes sense to split it up into multiple cookies.

**Comment by zandbelt** [comment]
That is a fair suggestion: I've done something similar for mod_auth_openidc in the past; https://github.com/pingidentity/mod_auth_openidc/issues/153

**Comment by iperdomo** [comment]
I just got hit by this issue while trying to make a sample using lua-resty-openidc & [Keycloak](http://www.keycloak.org). A full _debug log_ of the infinite redirect can be found at: 
https://gist.github.com/iperdomo/3a0a6401000b07cddf9737e4ec8aadd0

I didn't realize that was to the fact that the cookie was too big and browser won't store it.

**Comment by zandbelt** [comment]
Ok, thanks for chiming in; on the short term I'll look to issue a clear warning about size limits, on the mid-term I'll implement chunked cookies. Of course PRs are welcome...

**Comment by bungle** [comment]
@iperdomo,

I have now implemented chunked cookie support in `lua-resty-session` that this `lua-resty-openidc` depends on.

Just grab the latest `session.lua` from here:
https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session.lua

Also you may need to add something like this to your `nginx.conf`:

```nginx
large_client_header_buffers 4 16k;
```

**Comment by iperdomo** [comment]
@bungle thanks for your support. I patched my example with the code at rev 67b8354 and I can confirm that the infinite loop is gone. In my case the cookie was chunked in 2 pieces.

![2017-02-12-151637_1335x176_scrot](https://cloud.githubusercontent.com/assets/178474/22862833/83510156-f136-11e6-83d4-9e9727c0a2ee.png)

**Comment by zandbelt** [comment]
Same thing for me, a quick test works; I got my - artificially enlarged - session cookie split across for `Set-Cookie` headers and they were all provided and assembled back from a single `Cookie` header in the subsequent request.

**Comment by bungle** [comment]
@iperdomo / @zandbelt,

Thank you for further testing this out. I will soon prepare a new release of `lua-resty-session` that has a support for chunked cookies.

**Comment by zandbelt** [comment]
@bungle @iperdomo thanks; closing the issue here now
