### ISSUE TITLE
OPM Question

### ISSUE THREAD

**Issue by Phrozyn** [pingidentity/lua-resty-openidc#38]
Do you plan on adding this nifty module to OPM?
Just wondering because it would be nice to have.
Thanks!

**Comment by zandbelt** [comment]
I'm not familiar with OPM yet. Would you be able to confirm that the commit above handles the basics?

**Comment by Phrozyn** [comment]
Perfect :) 

Thanks so much! This will definitely increase our workflow efficiency and could possibly attract more users!
