### ISSUE TITLE
session state doesn't match state

### ISSUE THREAD

**Issue by ConanMalone** [pingidentity/lua-resty-openidc#39]
I keep getting this error when trying to configure openidc 

```openidc.lua:294: authenticate(): state from argument: adf7c9545d2d880ec073c96b63da7a60 does not match state restored from session: nil```

Note I have the latest version of lua-resty-session installed as I have read that the ```session_check_ssi``` has caused problems in the past... any ideas?

**Comment by zandbelt** [comment]
Hard to tell without context/versions/logs/plaform information. Could it be that you're accessing the protected application over plain http but the redirect_uri is set on secure https?

**Comment by tsyrjanen** [comment]
For example following works in my browser

http://my.kong.com/example_path

Then I try

http://my.kong.com/example_pathstate=cfc3da49a6df5c2aec74e4be69666fca&code=Df1HavlISrQqpPru-Hfg1VqvJ9INSt43SUNOj02qrLA.8f4adcf1-7a4a-4e79-ad7a-362e9c56caca

I get

state from argument: cfc3da49a6df5c2aec74e4be69666fca does not match state restored from session: nil

**Comment by zandbelt** [comment]
That 2nd URL including `code` and `state` is only supposed to be triggered once, upon return from the Provider; you can't "replay" a `code`(e.g. using browser "back") since it one time usage only

**Comment by sumantfordev** [comment]
I am getting the same issue, after authentication is completed, it redirects back to my nginx server with the url
http://10.164.44.38:84/redirect_uri?state=956e10313746f7fd3099accb8b3b2a1f&code=1sITigCe8sezDka-6_xIdcYhn1qGrYiTLamnwQbZ0C4.fd16ad62-aff0-4dd7-b25b-96c28947846d

But it says 

state from argument: 956e10313746f7fd3099accb8b3b2a1f does not match state restored from session: nil

**Comment by zandbelt** [comment]
Would you be able to capture/send a browser trace and a full debug log?

**Comment by sumantfordev** [comment]
figured the issue,lua_code_cache off makes sessions disappear.
fix would be to use a secret key to when a session is started.

**Comment by zandbelt** [comment]
I'll make a direct reference in the README to:
https://github.com/bungle/lua-resty-session#notes-about-turning-lua-code-cache-off

**Comment by ConanMalone** [comment]
Hasn't solved the problem for my setup.  Here is my nginx.conf file does it look like there's anything wrong?

```
error_log logs/error.log debug;


events {
  worker_connections 1024;
}

http {

  lua_package_path '~/lua/?.lua;;';

  resolver 192.168.60.1;

  lua_ssl_trusted_certificate /etc/ssl/certs/ca-bundle.crt;
  lua_ssl_verify_depth 5;

  # cache for discovery metadata documents
  lua_shared_dict discovery 1m;

  include /usr/local/openresty/nginx/conf/mime.types;

  server {

    listen 443;
    server_name myserver.domain.com;

    index index.php index.html index.htm;

    ssl                  on;
    ssl_certificate      /etc/nginx/ssl/myserver.domain.cer;
    ssl_certificate_key  /etc/nginx/ssl/myserver.domain.key;
    set $session_check_ssi off;
    set $session_storage memcache;
    set $session_secret BNnDSJDS9ASJDIedk2ndkNDMksndk89;

location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }


    location /protected {

      access_by_lua '

          local opts = {
             -- the full redirect URI must be protected by this script and becomes:
             -- ngx.var.scheme.."://"..ngx.var.http_host..opts.redirect_uri_path
             -- unless the scheme is overridden using opts.redirect_uri_scheme or an X-Forwarded-Proto header in the incoming request
             redirect_uri_path = "/protected/redirect_uri",
             discovery = "https://idp.domain.com/.well-known/openid-configuration",
             client_id = "openresty-lua-opeidc",
             client_secret = "maKiagfdag52vxj690dsdsHVBhVSHdsHSuxxxxxz",
             --authorization_params = { },
             scope = "openid email profile",
             --iat_slack = 600,
             redirect_uri_scheme = "https"
             --logout_path = "/logout",
             --token_endpoint_auth_method = ["client_secret_basic"|"client_secret_post"]
             --ssl_verify = "no"
          }

          -- call authenticate for OpenID Connect user authentication
          local res, err = require("resty.openidc").authenticate(opts)

          if err then
            ngx.status = 500
            ngx.say(err)
            ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
          end

          -- at this point res is a Lua table with 3 keys:
          --   id_token    : a Lua table with the claims from the id_token (required)
          --   access_token: the access token (optional)
          --   user        : a Lua table with the claims returned from the user info endpoint (optional)

          --if res.id_token.hd ~= "pingidentity.com" then
          --  ngx.exit(ngx.HTTP_FORBIDDEN)
          --end

          --if res.user.email ~= "hans.zandbelt@zmartzone.eu" then
          --  ngx.exit(ngx.HTTP_FORBIDDEN)
          --end

          -- set headers with user info (overwriting any existing!)
          ngx.req.set_header("X-USER", res.id_token.sub)
      ';

      proxy_pass https://myserver.domain.com/protected;
    }
  }
}
```

**Comment by zandbelt** [comment]
Can you try with a different cache setting just to pin down the problem, i.e. comment out `set $session_storage memcache;`? Also, could you provide a full browser trace and server debug log?

**Comment by ConanMalone** [comment]
Okay I tried commenting out the session_storage and now this gives a 500 Internal Server error with this in the logs

```
2017/03/13 09:32:33 [debug] 22309#22309: *1011 [lua] openidc.lua:357: openidc_discover(): In openidc_discover - URL is https://idp.domain.com/.well-known/openid-configuration
2017/03/13 09:32:33 [debug] 22309#22309: *1011 [lua] openidc.lua:81: openidc_cache_get(): cache hit: type=discovery key=https://idp.domain.com/.well-known/openid-configuration
2017/03/13 09:32:33 [debug] 22309#22309: *1011 [lua] openidc.lua:504: openidc_get_token_auth_method(): 1 => client_secret_basic
2017/03/13 09:32:33 [debug] 22309#22309: *1011 [lua] openidc.lua:506: openidc_get_token_auth_method(): configured value for token_endpoint_auth_method (client_secret_basic) found in token_endpoint_auth_methods_supported in metadata
2017/03/13 09:32:33 [debug] 22309#22309: *1011 [lua] openidc.lua:528: openidc_get_token_auth_method(): token_endpoint_auth_method result set to client_secret_basic
2017/03/13 09:32:33 [debug] 22309#22309: *1011 [lua] openidc.lua:574: authenticate(): id_token={"oxOpenIDConnectVersion":"openidconnect-1.0","iss":"https:\/\/idp.domain.com","nonce":"70c3098feb7ffcc52db7d5ae1ab5bd40","iat":1489397400,"aud":"openresty-lua-opeidc","exp":1489401000,"oxValidationURI":"https:\/\/idp.domain\/oxauth\/opiframe","auth_time":1489392325,"sub":"@!1C46.38AE.D077.C150!0001!849C.7440!0000!3B7E.9EC2","at_hash":"LjpC8aeNXU26x7XMBLRMAA"}
2017/03/13 09:32:33 [crit] 22309#22309: accept4() failed (24: Too many open files)
2017/03/13 09:32:33 [crit] 22309#22309: accept4() failed (24: Too many open files)
2017/03/13 09:32:34 [crit] 22309#22309: accept4() failed (24: Too many open files)
2017/03/13 09:32:34 [crit] 22309#22309: accept4() failed (24: Too many open files)
2017/03/13 09:32:35 [crit] 22309#22309: accept4() failed (24: Too many open files)
2017/03/13 09:32:35 [crit] 22309#22309: accept4() failed (24: Too many open files)
2017/03/13 09:32:36 [crit] 22309#22309: accept4() failed (24: Too many open files)
...
```
The too many open files just goes on

**Comment by zandbelt** [comment]
are you seeing a loop before that?

**Comment by ConanMalone** [comment]
No when I had the session_storage uncommented I wasn't seeing any loop

**Comment by zandbelt** [comment]
Are you sure you need `             redirect_uri_scheme = "https"`? If so it may be associated with the root cause. It should work without.

**Comment by ConanMalone** [comment]
Tried removing that and still getting the same error

**Comment by zandbelt** [comment]
Would you be able to try with a minimized `nginx.conf` i.e. the one in the `README.md`?

**Comment by ConanMalone** [comment]
Got it working now with a minimized ```nginx.conf``` not sure what the problem was there

**Comment by jeromegn** [comment]
I'm also facing this issue. I'm using the default cookie store and I often get the same error:

```
state from argument: f26363cb4ae4986012a86d27f4759862 does not match state restored from session: nil
```

when hitting: `/auth/google/callback?state=f26363cb4ae4986012a86d27f4759862&code=4/MpfTAuTmq8C0slI_v6JF6t05uFuS7yx12WDSmdl45LI&authuser=0&hd=fly.io&session_state=6bc39d055da9d248b81c36fab4fc8d6e66c0611c..1b71&prompt=none` after a redirect.

I'm using:
- Version: 1.3.0
- Openresty version: 1.11.2.2
- OS: Alpine 3.5

Here's what my setup looks like:

```lua
    local opts = {
      redirect_uri_path = "/auth/google/callback",
      discovery = "https://accounts.google.com/.well-known/openid-configuration",
      client_id = "<my client id>",
      client_secret = "<my client secret>",
      authorization_params = { hd = "mydomain.com" },
      scope = "openid email",
      ssl_verify = "no"
    }

    local res, err = core.openidc.authenticate(opts)
```

I'm running the above in a `content_by_lua_block`

**Comment by zandbelt** [comment]
Would it be possible to try your setup in a minimize config? And do this in an `access_by_lua` block?

**Comment by jeromegn** [comment]
I could, but I do need to run this in a `content_by_lua` block at the moment.

What's weird is that it works most of the time. Then it'll stop working for a few requests and then back to working again. Sometimes it will just be assets (like a favicon) that won't be loading anymore because of the aforementioned error.

Initially I thought I was having `math.random` collisions and so I started seeding a unique number with `math.randomseed` for each of my nginx workers.

Given that all examples in the `lua-resty-session` repo seem to use `content_by_lua`, I can't imagine that would be an issue.

**Comment by zandbelt** [comment]
Could you check the actual system limits as requested above? FWIW: all the examples use `access_by_lua`.

**Comment by jeromegn** [comment]
I may have missed your comment about checking the system limits (I viewed the comment really quickly after you posted it initially.)

Here's what the machine shows:

```
bash-4.3$ sysctl -a | grep fs.file-max
fs.file-max = 3281505
```

and my nginx config:

```
worker_rlimit_nofile 1048576;
```

That number was determined by `ulimit -n` of my system (which is `1048576`.)

My logs don't show any "Too many files open" errors.

At this time, putting this in the `access_by_lua` block would require a big refactor. I mentioned that *`resty.session`* examples were all in `content_by_lua` and I believe the current issue is a session-related one.

FWIW, both 1.3.0 and master showed the same issue.

Is there a state being kept somewhere outside of the session? I can't reproduce the issue locally, it only happens in production for us. It'll work fine for a bunch of requests and then if I refresh after "some" (can't exactly tell) time has passed, it'll break again. It resolves itself if I keep hitting the original URL, eventually.

The main differences between my local environment and production environment are the OS (local is macOS Sierra), worker rlimit and number of workers (1 locally, 32 in production.) A request can hit either server we have running, so that's 64 workers than could handle a request. I don't think that would be a problem, but worth mentioning.

**Comment by jeromegn** [comment]
@zandbelt ok, it looks like it might be the same problem as the `lua_code_cache off;` directive.

Since we have more than one server, the session id will be different and therefore it won't be able to decode it from one request to another if it hits a different server.

We just set a fixed session_secret on all our servers (temporarily) to test this assumption. Seems fine for now.
