### ISSUE TITLE
question about session cookie expiration

### ISSUE THREAD

**Issue by consultantRR** [pingidentity/lua-resty-openidc#4]
I am finding that some browsers don't expire session cookies even when the browser is quit an relaunched. I don't want them to persist that long.

I tried these lua-resty-session settings:

set $session_cookie_renew      600;
set $session_cookie_lifetime   3600;

But the cookie that session cookie set by lua-resty-openidc still seems to show "session" expiration, and the above settings seem to have no effect.

Am I misusing these settings, or is there perhaps a better approach to shorter term invalidation and/or expiration of lua-resty-openidc sessions?

**Comment by consultantRR** [comment]
Sorry, following up on my own post. If I enable:

set $session_cookie_persistent on;

...along with the above settings, then expiration time is in effect.

However, I still think I may be going about this in the wrong way, and would appreciate any thoughts on better practice for guarding against too-long lived sessions without having to build out a full fledged invalidation mechanism in any upstream user apps.

**Comment by zandbelt** [comment]
This is really a question for the lua-resty-session project but the documentation at https://github.com/bungle/lua-resty-session#number-sessioncookielifetime suggests that you're on the right track. Alternatively you could use `ssl_session_timeout` as documented here: https://github.com/bungle/lua-resty-session#nginx-configuration-variables
