### ISSUE TITLE
Feature Request: Please add SAML support

### ISSUE THREAD

**Issue by mingfang** [pingidentity/lua-resty-openidc#40]

**Comment by mingfang** [comment]
I built SAML support using Passport SAML https://github.com/mingfang/docker-knginx/blob/master/saml/saml.lua

But would be nicer to add SAML your lua-resty-openidc so that it can be a one stop shop.

**Comment by zandbelt** [comment]
Feel free to do this as part of your own fork but supporting protocols other than OpenID Connect is outside of the scope of this project. Also feel free to suggest changes that would allow you to help you to maintain that fork with less effort.
