### ISSUE TITLE
Is the client_secret for Google+ Signin and the secret for JWT the same thing?

### ISSUE THREAD

**Issue by dimitrovs** [pingidentity/lua-resty-openidc#41]
I have a scenario where I want to use the redirect-based approach most of the time, but in one case I need to do CORS from JavaScript. If I create another endpoint using the JWT config, can I pass a jwt from the client and have lua-resty-openidc verify it with the client_secret? My signature algorithm is HS256. The client obtains the jwt token through a different path (which doesn't involve nginx).

**Comment by zandbelt** [comment]
You should be able to use a config similar to:
https://github.com/pingidentity/lua-resty-openidc#sample-configuration-for-oauth-20-jwt-token-validation

**Comment by dimitrovs** [comment]
But are the client_secret and secret referring to the same string?

**Comment by zandbelt** [comment]
Not by OAuth 2.0 spec. You'll have to check what the provider uses to sign the OAuth 2.0 access token.

Note: when it comes to the `id_token` that is defined in OpenID Connect that's a different story: by spec that is signed with a left-truncated hash of the client secret, see: http://openid.net/specs/openid-connect-core-1_0.html#Signing

But as said OAuth 2.0 does not specify the format access token itself nor its protection.
