### ISSUE TITLE
Issue in using UAA as OpenId provider

### ISSUE THREAD

**Issue by mohitmutha** [pingidentity/lua-resty-openidc#42]
When using UAA the url openid configuration URL of UAA http://<host>/uaa/.well-known/openid-configuration returns a JSON where the issuer field has value http://<host>/uaa/oauth/token 

This fails the validation in the openidc.lua and gives a error "issuer field in Discovery data does not match URL". Instead of checking for the full URL if the validation is changed to checking only for the host name then we would be able to use the script with OpenId as well.

**Comment by zandbelt** [comment]
The OpenID Connect specification requires that the issuer matches the Discovery URL, see: http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation

Hence the Provider should be fixed.

If you want to get around this for the short term you can modify the lua-resty-openidc code yourself but obviously it will not be included as part of the standard repository.
