### ISSUE TITLE
Mismatched state error

### ISSUE THREAD

**Issue by wjessop** [pingidentity/lua-resty-openidc#44]
I'm getting an error related to sessions:

`2017/03/23 01:01:26 [error] 11317#0: *1 [lua] openidc.lua:294: authenticate(): state from argument: 4ba273aded3294e5684674a39fe778cce23f84ead624db4b does not match state restored from session: a60dd9fb58feda4d72eee2af52a79789, client: 10.0.1.26, server: <snip>.com, request: "GET /auth/google/callback?state=4ba273aded3294e5684674a39fe778cce23f84ead624db4b&code=4/PvFKMkF62CiOupt3aRQC3PHanzlvV0NDh2dJnMwqYeo HTTP/1.1", host: "<snip>.com"`

My relevant Nginx config is:

```
location / {
    set $session_secret <snip>;
    access_by_lua '

      local opts = {
         -- the full redirect URI must be protected by this script and becomes:
         -- ngx.var.scheme.."://"..ngx.var.http_host..opts.redirect_uri_path
         -- unless the scheme is overridden using opts.redirect_uri_scheme or an X-Forwarded-Proto header in the incoming request
         redirect_uri_path = "/auth/google/callback",
         discovery = "https://accounts.google.com/.well-known/openid-configuration",
         client_id = "snip.apps.googleusercontent.com",
         client_secret = "snip",
         authorization_params = { hd="snip.com" },
         --scope = "openid email profile",
         --iat_slack = 600,
         --redirect_uri_scheme = "https",
         --logout_path = "/logout",
         --token_endpoint_auth_method = ["client_secret_basic"|"client_secret_post"],
         ssl_verify = "no"
      }

      -- call authenticate for OpenID Connect user authentication
      local res, err = require("resty.openidc").authenticate(opts)

      if err then
        ngx.status = 500
        ngx.say(err)
        ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
      end

      -- at this point res is a Lua table with 3 keys:
      --   id_token    : a Lua table with the claims from the id_token (required)
      --   access_token: the access token (optional)
      --   user        : a Lua table with the claims returned from the user info endpoint (optional)

      --if res.id_token.hd ~= "pingidentity.com" then
      --  ngx.exit(ngx.HTTP_FORBIDDEN)
      --end

      if res.user.email ~= "@snip.com" then
        -- ngx.exit(ngx.HTTP_FORBIDDEN)
      end

      -- set headers with user info (overwriting any existing!)
      ngx.req.set_header("X-USER", res.id_token.sub)
    ';

    try_files $uri @app;
    break;
  }
```

I did try `set $session_secret snip;` in the server{} block, and also memcached for sessions but stil get this error. The environment is on AWS behind an ELB that does SSL termination and forwards the decrypted traffic to nginx on port 80. For the time being I've limited the backend to one server which is running Nginx with `worker_processes      1;`. I also tried turning off the lua code cache, but to no avail.

Any help with this would be welcome.

**Comment by zandbelt** [comment]
Could you post a browser trace and a server debug log?

**Comment by wjessop** [comment]
I can try, what are they?

On the assumption that a server debug log [is this](http://nginx.org/en/docs/debugging_log.html) I will start a new compile of our Nginx server.

**Comment by zandbelt** [comment]
I believe default builds would be done with debugging enabled.

**Comment by wjessop** [comment]
OK, it looks like I was doing something wrong, I think redirecting in the app to google auth too as well as in openresty. Thanks for the help!
