### ISSUE TITLE
lua-resty-jwt broken, prevents lua-resty-openidc install

### ISSUE THREAD

**Issue by wjessop** [pingidentity/lua-resty-openidc#46]
0.1.10 of lua-resty-jwt [is broken](https://github.com/SkyLothar/lua-resty-jwt/issues/62) and is preventing the installation of lua-resty-openidc. I'm not sure the best solution here, as far as I can see there is no way to specify a version that should be excluded inside a range of versions inside a rockspec file. It should be possible to change the dependency version spec to:

    "lua-resty-jwt >= 0.1.5, < 0.1.10",

but this would prevent using versions of lua-resty-jwt later than 0.1.10. You could revert the change when a fix to lua-resty-jwt is released? Anyway, not too sure what to do here, thoughts?

**Comment by zandbelt** [comment]
thanks for reporting, let me think about the best way forward; I'm actually hoping for it to be fixed in lua-resty-jwt though...

**Comment by wjessop** [comment]
A workaround I'm using for now is to specifically install the previous version of lua-resty-jwt (0.1.9) before installing lua-resty-openidc:

    $ luarocks install lua-resty-jwt 0.1.9
    $ luarocks install lua-resty-openid

**Comment by tsyrjanen** [comment]
I reported the problem to lua-resty-jwt (https://github.com/SkyLothar/lua-resty-jwt/issues/62). Now they have fixed it.

**Comment by zandbelt** [comment]
cool, thanks for the heads-up; I'm assuming everyone will get the latest version automatically and we can close this?
