### ISSUE TITLE
Getting session not found, when updated to 1.3.1, not the case before

### ISSUE THREAD

**Issue by sureshvarman** [pingidentity/lua-resty-openidc#48]
FYI, Using with kong, and having multiple instance of kong running and clustered

**Comment by zandbelt** [comment]
Which version did you upgrade from and which session/caching mechanism are you using?

**Comment by sureshvarman** [comment]
upgraded from 1.3.0-1, using redis for session

**Comment by zandbelt** [comment]
I don't see any changes that may have caused this: https://github.com/pingidentity/lua-resty-openidc/compare/v1.3.0...v1.3.1

The only thing I can think of is that [`lua-resty-session`](https://github.com/bungle/lua-resty-session) was updated to a newer release alongside of the upgrade. Can you confirm that?

**Comment by sureshvarman** [comment]
In both cases it uses lua-resty-session 2.15 (latest), so i dont think there is a problem in that, anyway, Since there is no big changes, closing it now, will reopen, if i find the root cause or a solutions
