### ISSUE TITLE
Question on JWT Token Validation

### ISSUE THREAD

**Issue by venkatmarepalli** [pingidentity/lua-resty-openidc#49]
I am trying to validate my access_token using https://github.com/pingidentity/lua-resty-openidc#sample-configuration-for-oauth-20-jwt-token-validation-1. Somehow I wasn't able to succeed. My goal is to protect my apis using this approach. Here is my configuration. Am I missing something here. I am getting 2 issues here. Can someone tell me where I am going wrong. I was able to verify the signature using jwt.io

1. With the below configuration, I am getting  `openidc_discover(): accessing discovery url (https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration) failed: 20: unable to get local issuer certificate, client:`

2. When I added secret (public key string from my secret.crt file) I am getting `"reason":"Verification failed","raw_header":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InowMzl6ZHNGdWl6cEJmQlZLMVRuMjVRSFlPMCIs`

```
location /api {
      access_by_lua '
          local opts = {
            -- The jwks endpoint must provide a x5c entry
   discovery = "https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration"
          }
          -- call bearer_jwt_verify for OAuth 2.0 JWT validation
          local res, err = require("resty.openidc").bearer_jwt_verify(opts)
..
..
    }
  }
}
```

I am sending Curl request with authorization token to test if my /api is secured or not like below 
`curl -i http://myserver.com/api/index.html -H 'Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InowMzl6ZHNGdWl6cEJmQlZLMVRuMjVRSFlPMCIs'`

**Comment by zandbelt** [comment]
That looks like an issue with your SSL CA trust store. You can verify in a test setup by using `opts.ssl_verify=no` and it should work. For production usage you should fix this by pointing `lua_ssl_trusted_certificate ` to the right CA trust store. See also: https://github.com/pingidentity/lua-resty-openidc/issues/2 and https://github.com/openresty/lua-nginx-module#lua_ssl_trusted_certificate

**Comment by venkatmarepalli** [comment]
I don't think that is the issue because jwt.io is able to validate the signature. Do we have to provide secret in conf file ?

**Comment by zandbelt** [comment]
Your log shows that `lua-resty-openidc` tries to pull the Discovery metadata - which contains the configuration of the Provider - from `https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration` and that fails.

If that would succeed it would be able to pull the key material from the `jwks_uri` in there.

But it doesn't succeed because it cannot validate the SSL certification presented on `login.microsoftonline.com`. That indicates an error in your SSL CA setup.

**Comment by zandbelt** [comment]
If you have received the public key out-of-band you can configure it in the conf file as well in the way specified here: https://github.com/pingidentity/lua-resty-openidc#sample-configuration-for-oauth-20-jwt-token-validation

**Comment by venkatmarepalli** [comment]
I am hitting into this issue when I try with ssl_verify="no" any pointers? Appreciate your quick response.

```
2017/05/05 11:56:55 [debug] 11670#0: *86 [lua] openidc.lua:692: bearer_jwt_verify(): bearer_jwt_verify using discovery.
2017/05/05 11:56:55 [debug] 11670#0: *86 [lua] openidc.lua:358: openidc_discover(): In openidc_discover - URL is https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration
2017/05/05 11:56:55 [debug] 11670#0: *86 [lua] openidc.lua:364: openidc_discover(): Discovery data not in cache. Making call to discovery endpoint
2017/05/05 11:56:55 [debug] 11670#0: *86 [lua] http.lua:610: send_request(): 
GET /common/v2.0/.well-known/openid-configuration HTTP/1.1
Host: login.microsoftonline.com
User-Agent: lua-resty-http/0.10 (Lua) ngx_lua/10007


nginx: lua atpanic: Lua VM crashed, reason: ...ols/public/openresty/1.11.2.2/site/lualib/resty/http.lua:661: attempt to call global 'def_pcall' (a nil value)
2017/05/05 11:56:56 [notice] 11670#0: gracefully shutting down
2017/05/05 11:56:56 [notice] 11670#0: exiting
```

**Comment by zandbelt** [comment]
seems like your local installation is somehow messed up; I'd advise you to try with the stock sample and work your way back from there

**Comment by venkatmarepalli** [comment]
I am returning the access_token to the browser after authentication using `res.access_token`. Now when I pass the same access_token to `bearer_jwt_verify()` method, it throws `invalid jwt`. 

I believe `res.access_token` is the bearer token and `bearer_jwt_verify()`  is for verifying bearer access tokens.

**Comment by venkatmarepalli** [comment]
I noticed that the behaviour of Azure AD Native app and Webapp are different while redirecting users back to the request uri after authnetication. Anyone know why there is a different behaviour.

For Example: When I try to navigate to `www.server.com/api/index.html` which is secured in nginx it is going to Microsoft login page and once logged in going to `index.html` whereas for native applications it is throwing an error which says the redirect url `/secured` doesn't match with the one configured in Azure AD. Any pointers on this?
