### ISSUE TITLE
Interaction required error from token end point

### ISSUE THREAD

**Issue by venkatmarepalli** [pingidentity/lua-resty-openidc#50]
I am getting this issue suddenly. not sure why I am getting this. We are working with Microsoft azure OAuth. Can someone tell how you fixed this issue? I referred to issue #8 where it was fixed by redirecting the user to original url. Can you paste the sample code that can be used in nginx.conf file to fix this ?
 
The below error is coming from `openidc_call_token_endpoint ` method. We should redirect the user to Microsoft auth page whenever `interaction_required `error is seen, once he completes the additional authentication then bring him back.

`response indicates failure, status=400, body={"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000002-0000-0000-c000-000000000000'.\r\nTrace ID: 5889afab-8ce9-40da-b5fb-c76b4f420000\r\nCorrelation ID: 215515f1-8f10-4ed6-b4a8-fda77d259dcc\r\nTimestamp: 2017-05-09 23:30:44Z","error_codes":[50076],`

We have MFA setup within our org. during the initial authentication microsoft automatically takes to OTP page and completes the authentication but not sure from where this interaction_ required error is hit again. I have 2 machines in different locations, the flow is working fine from one machine where OTP page is shown, but it is not working from other location where OTP page is not shown. Hope my explanation is clear

**Comment by zandbelt** [comment]
I assume this error is produced by the authorization endpoint rather than the token endpoint. In that case it is out of control by the module: it is just a page that Azure produces.

**Comment by venkatmarepalli** [comment]
This error is coming after the user is logged in and is redirected to redirect uri.

**Comment by zandbelt** [comment]
It is really something that you'll need to solve in Azure AD.

**Comment by venkatmarepalli** [comment]
Not sure why it works from one machine and doesn't work on another. Also is there a way to redirect the user back to redirect path by keeping code, session_state and state query parameters intact? When my page is redirected I am seeing an error which says `request to the redirect_uri_path but there's no session state found`

**Comment by zandbelt** [comment]
apparently, interpreting the error message, Azure AD takes into account the IP address of the client and refuses one of them

**Comment by venkatmarepalli** [comment]
Thanks, I will check what is happening inside AD. Can you help me on the other question, I want authorization code in the query parameter after successful authentication. How can I redirect users back to a page which keeps auth code intact?

For Ex: User tries to access http://www.server.com authenticated and redirected back to http://www.server.com home page but I want to redirect to http://www.server.com/test.html?code=ddsfdf. here my test.html reads auth code and displays a javascript dialog to the user.

**Comment by zandbelt** [comment]
Change the registered redirect URI in Azure AD to your URL.

**Comment by venkatmarepalli** [comment]
That was it already, It works sometimes and sometimes it won't work. And now I am hitting this error suddenly, when it is redirecting back I am seeing code, session_state and state query params and the browser shows this error msg.

**Comment by venkatmarepalli** [comment]
I sent a POST request using postman tool to the token_endpoint from the same machine where I am getting `interaction_required` error using the same parameters that `openidc.lua` is using. It returned access_token and refresh_token successfully.

**Comment by zandbelt** [comment]
What do you want me to say: you're using the same parameters so there's no difference from the caller's perspective.

**Comment by venkatmarepalli** [comment]
Ok Found the issue. Try this location directive and you will see this interaction_required error from the server. `location ~ (\.cgi$|\.pdf$|\.html$|\.html.*|(^/(logout|secured)$)) { }` 
Though there are any issues with location regex I am not sure why this error is coming.

One more question. I was able to redirect back to the path which is configured in Azure AD but whenever I try to open any other url it is always taking me to the same redirect_url path. Fox example I access `www.server.com` and after authenticating redirected to `www.server.com/test`. If I access `www.server.com/secured/new`, I am taken to `www.server.com/test`. Is it something to do with location directives?

**Comment by zandbelt** [comment]
take a look at `local function openidc_get_redirect_uri(opts)`

**Comment by venkatmarepalli** [comment]
I have seen that I was wondering why it is always taking the redirect_uri_path mentioned in opts? Did I not understand it properly. I believe every request should go through authenticate function and come out with the same input url.

**Comment by venkatmarepalli** [comment]
https://github.com/pingidentity/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L562 
This conditions is checking `if path == redirect_uri_path`. I was wondering if this ever matches, because when I access www.server.com and my opts.redirect_path="/secured" it tried to match "/" with "/secured" and it won't match.
