### ISSUE TITLE
How about adding refresh_token to session data

### ISSUE THREAD

**Issue by sureshvarman** [pingidentity/lua-resty-openidc#51]
So whenver the userinformation are changed, we can always request new idtoken silently and update it to the session data.

**Comment by zandbelt** [comment]
One should not be able to request a new `id_token` using a refresh token, that's against the semantics of an `id_token`: the user should be present to authenticate himself.

What could be done is to refresh the access token and periodically poll the user info endpoint to update the data in the session with the claims from the user info endpoint in a similar way to mod_auth_openidc: https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L723

**Comment by sureshvarman** [comment]
http://openid.net/specs/openid-connect-core-1_0.html#RefreshingAccessToken. if i'm not wrong, Its not against the semantics, My IDP follows the guidelines as how the new refreshed id token should be issued, only the claims get changed in the IdToken. So getting refreshed id token is fine.

I don't want to periodically refresh, i want to force refresh, because in entire system flow, it is not possible to knew, when the user information is updated.

**Comment by zandbelt** [comment]
That section speaks about refreshing the access token only. Your IDP seems to extend the spec so you'll need to extend the RP client yourself if you want to follow that. Adding a hook for a forced refresh of an access token is something that can be added here.

**Comment by sureshvarman** [comment]
If an ID Token is returned as a result of a token refresh request, the following requirements apply:

its iss Claim Value MUST be the same as in the ID Token issued when the original authentication occurred,
its sub Claim Value MUST be the same as in the ID Token issued when the original authentication occurred,
its iat Claim MUST represent the time that the new ID Token is issued,
its aud Claim Value MUST be the same as in the ID Token issued when the original authentication occurred,
if the ID Token contains an auth_time Claim, its value MUST represent the time of the original authentication - not the time that the new ID token is issued,
its azp Claim Value MUST be the same as in the ID Token issued when the original authentication occurred; if no azp Claim was present in the original ID Token, one MUST NOT be present in the new ID Token, and
otherwise, the same rules apply as apply when issuing an ID Token at the time of the original authentication.

**Comment by gonzalad** [comment]
Hello, this feature would be very interesting to refresh the accessToken when it is expired : 
if we want to use the nginx as a RP for OAuth Resource Servers, the accessToken needs to be valid (and not expired).

The nginx could provide a method to get such a valid access token which :
 - would test the current AT validity (i.e. is it expired)
 - if expired silently call the refresh token endpoint if the current scope contains refreshToken and update accessToken in session.
 - return the valid accessToken.

Also there's a little window when : accessToken is not expired in OIDC RP and becomes expired in the RS side that could perhaps be handled (don't know how : i.e. provide a tolerance to artificially reduce the at expiry in the RP side or provide a way to trap 401, refresh the token and recall the RS).

Regards,
Adrian

**Comment by zandbelt** [comment]
agreed, feel free to submit a PR

**Comment by gonzalad** [comment]
Hello @zandbelt , I just created a PR for this issue.
If there's anything I should change, please tell me !
Thanks,
Adrian

**Comment by zandbelt** [comment]
It looks pretty good so I have merged it. I have to do some testing myself and possibly fine-tune it before I put out a new release. I'll leave the ticket open until then. Thanks for now!

**Comment by gonzalad** [comment]
Thanks very much @zandbelt !
