### ISSUE TITLE
Misleading function signature openidc_authorization_response

### ISSUE THREAD

**Issue by nielsole** [pingidentity/lua-resty-openidc#69]
Hi,
I just tried to set up the project and ran into an error, that wasn't returned correctly. Below is my try at root cause analysis:
`openidc_authorization_response` returns `ngx.redirect(session.data.original_url), session`.
https://github.com/pingidentity/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L363
The first `ngx.redirect` is nil and the second is the session-table. This matches the usual `nil, err` guideline and is promptly misunderstood by the caller https://github.com/pingidentity/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L636 . 
Thereby the example code in the `README.md` would contain the `session` as `err` and `ngx.say` would probably fail because `session` is a table:
https://github.com/pingidentity/lua-resty-openidc

    local res, err = require("resty.openidc").authenticate(opts)

    if err then
      ngx.status = 500
      ngx.say(err)
      ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
    end

https://github.com/pingidentity/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L363

I have a working solution, but I am not yet sure it does the right thing in all cases and will hopefully make a pull-request eventually.

**Comment by zandbelt** [comment]
I believe you're right: the code seems off in a number of places wrt. returning the result.

**Comment by nielsole** [comment]
I just submitted a pull request as a proposal for discussion. 
In general I think it is more common in LUA to just throw errors instead of returning them!? Would that be a better solution here?
