### ISSUE TITLE
Question about reverse proxy

### ISSUE THREAD

**Issue by waldo2188** [pingidentity/lua-resty-openidc#70]
I use lua-resty-openidc for protecting some services in a docker environment. I’ve defined Nginx as a reverse proxy for protected Apps, everything works fine (in a really nice way).
Recently I would like to try the reverse proxy [traefik](traefik.io).

Now I tested the reverse proxy [traefik](traefik.io).
So, I put traefik in front of Nginx and traefik manage the ssl stuff. By this way Nginx is just here for protecting Apps and manage the OpenId Connect authentication. 
But with this configuration it did not work.

```
server { 
    listen       80;
    server_name  "kibana.acme.org";
    access_log off;

    location / {
        access_by_lua '
                local cjson = require "cjson"

                function inTable(tbl, item)
                    for key, value in pairs(tbl) do
                        if value == item then return key end
                    end
                    return false
                end

               local opts = {
                    redirect_uri_path = "/redirect_uri",
                    discovery = os.getenv("DISCOVERY"),
                    client_id = os.getenv("CLIENT_ID"),
                    client_secret = os.getenv("CLIENT_SECRET"),
                    scope = os.getenv("CLIENT_SCOPE"),
                    ssl_verify = os.getenv("SSL_VERIFY")
                }

                local res, err = require("resty.openidc").authenticate(opts)

                if err then
                    ngx.status = 500
                    ngx.say(err)
                    ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
                end

                if inTable(res.user.role, "admin_kibana") == false then
                  ngx.exit(ngx.HTTP_FORBIDDEN)
                end
            ';

        proxy_pass         http://to_elk_kibana:5601;
    }
}
```

Another strange thing I’ve seen during my tests. Each time the browser makes a GET request on a protected App, lua-resty-openidc make a call to the OpenId Connect Provider. I don’t know if it’s a normal behavior or a settings mistake?

**Comment by zandbelt** [comment]
Yeah, I don't think putting a reverse proxy in front of lua-resty-openidc is fully supported yet. It would mean adding something similar as:
https://github.com/pingidentity/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L138
for the `X-Forwarded-Host` header.

Not sure about 2nd issue; perhaps a debug log would make it clear what that call is.

**Comment by waldo2188** [comment]
Thank for the quick answer.
How can I configure a debug log for nginx?

**Comment by zandbelt** [comment]
http://nginx.org/en/docs/debugging_log.html

**Comment by waldo2188** [comment]
I've found the roots of the issue.
It is stupidly a question of cookie. Since I have put a secret for resty.session, everything work fine !
