### ISSUE TITLE
"invalid token: No trusted certs loaded", client: 10.12.147.129

### ISSUE THREAD

**Issue by cyf992002** [pingidentity/lua-resty-openidc#75]
Hello,
        I am using following code to verify the token from keycloak, 
`    local json, err, access_token = require("resty.openidc").bearer_jwt_verify(utils.get_options(config, ngx))`
      but an error was returned  "invalid token: No trusted certs loaded", can someone tell what certs needs to be load and how to load it? thanks

**Comment by zandbelt** [comment]
That seems to be an error generated by `lua-resty-jwt` when no secret/key has been configured. You'll need to set `opt.secret` or similar.
