### ISSUE TITLE
why  `exp` is special?

### ISSUE THREAD

**Issue by dereknex** [pingidentity/lua-resty-openidc#76]
The code as blow:
```lua
   if json then
      local expiry_claim = opts.expiry_claim or "expires_in"
      local ttl = json[expiry_claim]
      if expiry_claim ~= "exp" then --https://tools.ietf.org/html/rfc7662#section-2.2
        ttl = ttl - ngx.time()
      end
      openidc_cache_set("introspection", access_token, cjson.encode(json), ttl)
    end
```
I check [https://tools.ietf.org/html/rfc7662#section-2.2](https://tools.ietf.org/html/rfc7662#section-2.2) link, that's as blow:

```
exp
      OPTIONAL.  Integer timestamp, measured in the number of seconds
      since January 1 1970 UTC, indicating when this token will expire,
      as defined in JWT [RFC7519].
```

The `exp` is integer timestamp, isn't seconds from now.

**Comment by zandbelt** [comment]
the code actually sets the ttl to the absolute timestamp first; if then the claim name is **not** equal to `exp` then it is assumed that this is a non-standard type of introspection and it will assume that the value is a relative timestamp; so `exp` is not the special case, it is all other values

**Comment by dereknex** [comment]
Thank you for you reply.  I'm English is not good. I'm confused that 'exp' is standard and it is a  number of seconds since January 1 1970 UTC. Not a absolute timestamp.  keycloak is corrected. So I think if 'expiry_claim' == 'exp' need execute 'ttl = ttl - ngx.time()'. 



_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zandbelt** [comment]
The number of seconds since January 1 1970 is considered to be an absolute timestamp. A relative timestamp would be measured in seconds e.g. 600 seconds "from now". That's the spec, that's how lua-resty-openidc does it and I believe that's what Keycloak does as well reading: http://www.keycloak.org/docs/2.4/authorization_services_guide/topics/service/protection/token-introspection.html (search for "exp").

If you want different behavior you'll need to run a customized version of lua-resty-openidc.

**Comment by dereknex** [comment]
Thanks, I understand.

_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zandbelt** [comment]
After re-reading the code I think it is the wrong way around...

**Comment by dereknex** [comment]
I change it and run locally, code as below:
```lua
-- cache the results
    if json then
      if json.active then
        local expiry_claim = opts.expiry_claim or "expires_in"
        local ttl = json[expiry_claim]
--        if expiry_claim ~= "exp" then --https://tools.ietf.org/html/rfc7662#section-2.2
          ttl = ttl - ngx.time()
--        end
        openidc_cache_set("introspection", access_token, cjson.encode(json), ttl)
      else
        err = "invalid token"
      end
    end
```
It's looks fine.
