### ISSUE TITLE
Question: how to configure logout redirect

### ISSUE THREAD

**Issue by pgp44** [pingidentity/lua-resty-openidc#77]
Hello

I am trying to 'convert' a working mod_auth_openidc configuration to lua-resty-openidc.

Login is working, and so is logout, but I cannot seem to get the OP redirect to an application page after logout

With mod_auth_openidc I could do something like "callback?logout=<redirect url", but I can's find how to configure that using the combination of  'logout_path' and  'redirect_after_logout_uri'. I guess I need to specify it in redirect_after_logout_uri but that is not really working. 
Perhaps the id_token_hint is missing or something. THis is automagically provided using mod_auth_openidc.

All tips warmly welcomed!

Tx

Peter

**Comment by zandbelt** [comment]
It doesn't seem that it is really supported right now. What you can do is manually set/overrride `opts.discovery.end_session_endpoint` and add a `post_logout_redirect_uri` parameter that contains the URL you want to go to after the provider logs you out.

**Comment by pgp44** [comment]
Hello

Thanks for looking into this. Not sure I undertand the workaround though

If I compare mod_auth_openidc with the open resty lua behavior I see the following on logout
```
mod_auth_openidc
----------------
Browser sends: https://<appurl>/callback?logout=<redirect url>
302 -> https://<op url>/oidc/logout?id_token_hint=...&post_logout_redirect_uri=...
302 -> <redirect url>
```
All is well :)

```
open resty lua
--------------
The config has
  redirect_after_logout_uri = https://<op url>/oidc/logout?post_logout_redirect_uri=...
  logout_path = "/logout"

The "flow" is

Browser sends: https://<app url>/logout
302 -> https://<op url>/oidc/logout?post_logout_redirect_uri=...
302 -> https://<op url>/authenticationendpoint/oauth2_logout.do
```
An OP page saying logout is done - not so well :)

So the redirect url is specified and passed, but compared to mod_auth_openidc there is no id_token_hint. I am not sure but perhaps because of that the op does not redirect to the <redirect url> but to an OP logout endpoint

Do you expect that setting a  post_logout_redirect_uri  property in opts.discovery.end_session_endpoint will make a difference? I am a bit reluctant to try as I am a lua noob.

Thanks for any tips you might have!

Peter

**Comment by zandbelt** [comment]
You're right, that wouldn't make a difference. I guess the provider requires the `id_token_hint` then, which would require a code modification.

**Comment by pgp44** [comment]
Thanks.

I got something working with two extra lines in the logout function. Obviously this is not at all a generic solution, but at least the idea is clear I guess

```
-- handle logout
local function openidc_logout(opts, session)
    -- LOGOUT REDIRECT PATCH - Keep id_token for later id_token_hint
    local session_token = session.data.enc_id_token
  session:destroy()
  local headers = ngx.req.get_headers()
  local header =  headers['Accept']
  if header and header:find("image/png") then
    ngx.header["Cache-Control"] = "no-cache, no-store"
    ngx.header["Pragma"] = "no-cache"
    ngx.header["P3P"] = "CAO PSA OUR"
    ngx.header["Expires"] = "0"
    ngx.header["X-Frame-Options"] = "DENY"
    ngx.header.content_type = "image/png"
    ngx.print(openidc_transparent_pixel)
    ngx.exit(ngx.OK)
    return
  elseif opts.redirect_after_logout_uri then
    -- LOGOUT REDIRECT PATCH - Add id_token_hint  
    return ngx.redirect(opts.redirect_after_logout_uri.."&id_token_hint="..session_token)
  elseif opts.discovery.end_session_endpoint then
    return ngx.redirect(opts.discovery.end_session_endpoint)
  elseif opts.discovery.ping_end_session_endpoint then
    return ngx.redirect(opts.discovery.ping_end_session_endpoint)
  end

  ngx.header.content_type = "text/html"
  ngx.say("<html><body>Logged Out</body></html>")
  ngx.exit(ngx.OK)
end

```
