### ISSUE TITLE
not sure how to handle interaction_required

### ISSUE THREAD

**Issue by consultantRR** [pingidentity/lua-resty-openidc#8]
When using Google as an OP, I have been using `opts.authorization_params.prompt = "none"`, in cases where I am reauthorizing a recently authorized user, but want to do so in a way that is seamless/invisible to the user.

This works well except in a few rare cases, where the user has beeb independently logged out of Google in the brief time between first authorization to my app, and the reauthorization attempt using `opts.authorization_params.prompt = "none"`.

In those cases, Google sends back the following args (and only the following args) to the redirect url:

```
state=032b7b6bb5ba1daabe0abfa8eea75090  (for example)
&error_subtype=access_denied
&error=interaction_required
```

This, of course, throws the following error:

```
openidc.lua:256: authenticate(): unhandled request to the redirect_uri: /redirect_uri?state=032b7b6bb5ba1daabe0abfa8eea75090&error_subtype=access_denied&error=interaction_required
```

How would this best be handled? Ideally, I'd like to redirect back to Google with `opts.authorization_params.prompt = nil` so that the user can be prompted in this one case.

Is this kind of response something that maybe lua-resty-openidc could/should be prepared to handle?

**Comment by zandbelt** [comment]
yes, lua-resty-openidc needs to be extended with a handler for that error

**Comment by consultantRR** [comment]
In the meantime, this is what I just wrote externally in my script that calls resty-openidc:

```
              if ngx.var.arg_error == "interaction_required" then
                  opts.authorization_params = {}
                  local session = require "resty.session".open()
                  local orig_url = session.data.original_url or "/"
                  local orig_scheme = opts.redirect_uri_scheme or ngx.req.get_headers()['X-Forwarded-Proto'] or ngx.var.scheme
                  local redirect_to_orig = orig_scheme.."://"..ngx.var.http_host..orig_url
                  session:destroy()
                  return ngx.redirect(redirect_to_orig)
              end
```

**Comment by zandbelt** [comment]
it probably makes sense to keep the majority of that code in lua-resty-openidc perhaps by a callback in to userspace to a handler that the caller would have registered at initialization time or by handling an error like you do but at least it shouldn't need to open the session and should call a method on lua-resty-openidc to obtain the original URL

however, if the only thing that you would do is redirect with `opts.authorization_params = {}` then I don' t see why you wouldn't do that in the first place...

**Comment by consultantRR** [comment]
I think, ideally, the /redirect_uri endpoint of lua-resty-openidc would in this condition, simply redirect back to google (as it did the first time), but dropping authorization_params this time. (Or something similar...) No?

**Comment by zandbelt** [comment]
no, that would defeat the point of having and passing this parameter at first; the idea behind "prompt=none" is that it silently returns to the caller so that other "unauthenticated" actions can be taken; redirecting right away in interactive mode makes the earlier prompt=none obsolete

**Comment by consultantRR** [comment]
That is a good point. So, perhaps lua-resty-openidc could simply trap the condition, and return a predictable err (along with the original_url the user requested, if known by lua-resty-openidc) and let the caller decide what to do about that?

Although it's hard for me to imagine many scenarios where lua-resty-openidc _would_ know the original_url, since it seems like there would be very few cases that this redirect was being done while the session is still present and non-expired.

**Comment by zandbelt** [comment]
the latest commit should allow for easier handling as in:

```
    local res, err, original_url = require("resty.openidc").authenticate(opts)
    if err and (ngx.var.arg_error == "login_required" or ngx.var.arg_error == "interaction_required") then
        -- handle the case in which non-interactive login is not possible, e.g. by triggering interactive login now (which would not be a realistic action but just for demonstration purposes)
        opts.authorization_params = {}
        res, err = require("resty.openidc").authenticate(opts, original_url)
    end
```

let me know if that works for  you

**Comment by zandbelt** [comment]
does it work?

**Comment by consultantRR** [comment]
Sorry, I worked around this before this commit was done. As soon as I get a chance, though, I will test. Much thanks.

**Comment by venkatmarepalli** [comment]
I am hit by this issue suddenly. not sure why I am getting this. We are working with Microsoft azure OAuth . Can someone tell how you fixed this issue? When I tried to see the value of `ngx.var.arg_error` it came out to be null.   My error on the browser is as follows

`response indicates failure, status=400, body={"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000002-0000-0000-c000-000000000000'.\r\nTrace ID: 5889afab-8ce9-40da-b5fb-c76b4f420000\r\nCorrelation ID: 215515f1-8f10-4ed6-b4a8-fda77d259dcc\r\nTimestamp: 2017-05-09 23:30:44Z","error_codes":[50076],`

**Comment by jwierzbo** [comment]
@zandbelt it doesn't work
`original_url` has following value: `xxx.com/redirect_uri?error=interaction_required&error_description=AADB2C90077%3a+User+does+not+have+an+existing+session+and+request+prompt+parameter+has+a+value+of+%27None%27...`
so it always cause 404
