### ISSUE TITLE
JWT support for iat_slack/grace period

### ISSUE THREAD

**Issue by nielsole** [pingidentity/lua-resty-openidc#80]
We ares using the `openidc.jwt_verify` function and would like add some grace period to the expiration of the tokens. 

Currently there are two places where the expiration is checked:

1. https://github.com/pingidentity/lua-resty-openidc/blob/e451ed7d076e44541740bb524389a9aa31d5ce69/lib/resty/openidc.lua#L823
`jwt:verify(opts.secret, access_token, ...)`
2. https://github.com/pingidentity/lua-resty-openidc/blob/e451ed7d076e44541740bb524389a9aa31d5ce69/lib/resty/openidc.lua#L842
`if json.exp and json.exp < ngx.time() then`

I tried setting grace periods in for both of these checks and they seem redundant to me. What is the reason/edge case for 2. Could the check just be removed? 

Ways to set a grace period in 1. and 2.

1. pass {lifetime_grace_period = opts.iat_slack} as parameter _Probably should just be passed in by the caller (not this library). so no change is necessary_
2. We would need to add the grace period to the check:
```local slack=opts.iat_slack and opts.iat_slack or 120
-- check the token expiry
  if json then
    if json.exp and json.exp + slack < ngx.time() then
```
Checking in this way is already being done at another place in the code: https://github.com/pingidentity/lua-resty-openidc/blob/e451ed7d076e44541740bb524389a9aa31d5ce69/lib/resty/openidc.lua#L106

Solutions to this issue:
a) remove the check in L842 completely
b) add the iat_slack to the if-clause
c) ?

What are your thoughts on this?

**Comment by zandbelt** [comment]
I don't want to depend on the calller passing in the `exp` validator, hence the code at L842. The other validation is "more optional and less standard" and is left up the the caller.

**Comment by nielsole** [comment]
In our case the jwt:verify failed without passing in any validator. So it doesn't even run into the L842 code snippet. We only run into L842 when setting the {lifetime_grace_period = opts.iat_slack}

**Comment by zandbelt** [comment]
I believe that was added not too long ago:
https://github.com/SkyLothar/lua-resty-jwt/commit/d977a1974c3ace4de1ab4473c4e8cc9d81ca9953
and may not be in each deployment.

**Comment by nielsole** [comment]
Good to know.
So it would still make sense to change 842 to include the `iat_slack`?!

**Comment by zandbelt** [comment]
yes

**Comment by nielsole** [comment]
Pull request is in

**Comment by nielsole** [comment]
:+1:
