### ISSUE TITLE
Empty "prompt" request param on auth url

### ISSUE THREAD

**Issue by andreasBerre** [pingidentity/lua-resty-openidc#90]
lua-resty-openidc seems to add the "prompt" request parameter to the authorization url regardless of whether it has been set in the opts or not (defaulting to empty string if it has not been set). 

My OP doesn't like this behavior, failing with "invalid prompt". Removing the empty param fixes the problem. 

Would not adding this param if the value is empty be better behavior?

**Comment by zandbelt** [comment]
I do think your OP needs to be fixed to ignore empty parameters (curious as to which implementation would stumble over that...) but you are right that it is an unintended effect so I addressed it nevertheless.
