### ISSUE TITLE
allow internal subnets

### ISSUE THREAD

**Issue by w9n** [pingidentity/lua-resty-openidc#92]
It would be helpful to define subnets which are allowed to access the resources without authentication, similar to [http_access_module](http://nginx.org/en/docs/http/ngx_http_access_module.html), which doesnt work with this plugin. There is no access to the request headers in the [main routine](https://github.com/pingidentity/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L618). I would appreciate some help where this could be implemented.
go-gitea/gitea#2428

**Comment by zandbelt** [comment]
I don't think `lua-resty-openidc` should implement authentication methods that have already been implemented in other standard modules; I'd rather see the two work together. What is not working? AFAIK you should be able to specify `http_access` directives before you hit `lua-resty-openidc`.

**Comment by w9n** [comment]
I had some miss understanding. `lua-resty-openidc` works perfectly fine with `http_access`!
