### ISSUE TITLE
Do not try to use unsupported Auth method

### ISSUE THREAD

**Issue by betalb** [pingidentity/lua-resty-openidc#95]
If OIDC discovery returns a list of  `token_endpoint_auth_methods_supported`, and `token_endpoint_auth_method` option was not provided, do not pick first from the list of IdP supported methods, instead pick first supported by library.

https://github.com/pingidentity/lua-resty-openidc/blob/8c15adb55b2290c80808e98b9f1503941ea87376/lib/resty/openidc.lua#L545

Out of 4 methods, described in discovery spec (`client_secret_post`, `client_secret_basic`, `client_secret_jwt`, and `private_key_jwt`) looks like only first 2 are actually supported.

Also it will be more clear if validation will be done against supplied `token_endpoint_auth_method`, that it is actually supported by library, not only that it is present in discovery response.

**Comment by bodewig** [comment]
@betalb I think #96 should solve this.
